name:                MiniRacket
version:             0.1.0.0
github:              "githubuser/MiniRacket"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         "Stack template project for COMP 3351"

dependencies:
- base >= 4.7 && < 5
- hspec

default-extensions:
-  EmptyCase
-  FlexibleContexts
-  FlexibleInstances
-  InstanceSigs
-  MultiParamTypeClasses
-  LambdaCase
-  MultiWayIf
-  NamedFieldPuns
-  TupleSections
-  DeriveFoldable
-  DeriveFunctor
-  DeriveGeneric
-  DeriveLift
-  DeriveTraversable
-  DerivingStrategies
-  GeneralizedNewtypeDeriving
-  StandaloneDeriving
-  BangPatterns
-  KindSignatures
-  TypeOperators
-  OverloadedStrings
-  ScopedTypeVariables
-  TypeApplications
-  ConstraintKinds

library:
  source-dirs: src

executables:
  MiniRacket-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    - -W
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - MiniRacket

tests:
  MiniRacket-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    - -W
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - MiniRacket
